// <auto-generated />
using System;
using CinemaApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaApp.Data.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    [Migration("20241003090932_AddCinemasToMovies")]
    partial class AddCinemasToMovies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CinemaApp.Data.Models.Cinema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Cinemas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d26d6ab5-098d-4280-bdaf-c9c1a63cf5da"),
                            Location = "Sofia",
                            Name = "Cinema City"
                        },
                        new
                        {
                            Id = new Guid("cb4b47fa-c0cb-4633-a954-f217119b95e3"),
                            Location = "Plovdiv",
                            Name = "Cine Grand"
                        },
                        new
                        {
                            Id = new Guid("04189060-0379-4c51-b344-8996137dda4a"),
                            Location = "Varna",
                            Name = "Cine Max"
                        },
                        new
                        {
                            Id = new Guid("54094914-1b0b-49e2-8d1b-08378ce1ce5d"),
                            Location = "Burgas",
                            Name = "Cine Grand"
                        },
                        new
                        {
                            Id = new Guid("dcd65071-6dde-46be-bf4e-836121dbd720"),
                            Location = "Ruse",
                            Name = "Cine Grand"
                        },
                        new
                        {
                            Id = new Guid("331bb93d-e18f-42c9-8d1d-e03c2681f9e1"),
                            Location = "Stara Zagora",
                            Name = "Cine Grand"
                        },
                        new
                        {
                            Id = new Guid("acc2f18d-1291-46ac-9e7d-e5b5093451a7"),
                            Location = "Pleven",
                            Name = "Cine Grand"
                        },
                        new
                        {
                            Id = new Guid("4573875d-7a2a-4986-9269-34301ba1a1e3"),
                            Location = "Sliven",
                            Name = "Cine Grand"
                        },
                        new
                        {
                            Id = new Guid("3051ac95-2f8d-4b9e-ac0d-16efcc1f9203"),
                            Location = "Dobrich",
                            Name = "Cine Grand"
                        },
                        new
                        {
                            Id = new Guid("af0324e0-bfa1-4512-a869-282fab48b9ca"),
                            Location = "Shumen",
                            Name = "Cine Grand"
                        },
                        new
                        {
                            Id = new Guid("ffdfe74a-de4f-409a-bb70-c7b8f084d6c9"),
                            Location = "Pernik",
                            Name = "Cine Grand"
                        },
                        new
                        {
                            Id = new Guid("efe1e59b-850d-4dc3-8c63-a6f0a8a54453"),
                            Location = "Haskovo",
                            Name = "Cine Grand"
                        },
                        new
                        {
                            Id = new Guid("1b19e0be-1e02-43bc-ba72-1da07d94a3e2"),
                            Location = "Yambol",
                            Name = "Cine Grand"
                        },
                        new
                        {
                            Id = new Guid("2b9bba32-1147-46cc-8565-094f0f79e7f1"),
                            Location = "Pazardzhik",
                            Name = "Cine Grand"
                        },
                        new
                        {
                            Id = new Guid("4ccf9cf6-e296-4fc5-81f4-69d43491285f"),
                            Location = "Blagoevgrad",
                            Name = "Cine Grand"
                        },
                        new
                        {
                            Id = new Guid("55ae2f15-bb09-4bc7-a6bd-516a53526728"),
                            Location = "Veliko Tarnovo",
                            Name = "Cine Grand"
                        },
                        new
                        {
                            Id = new Guid("36041389-ba8d-45be-8aaa-26a68adfd1cd"),
                            Location = "Vratsa",
                            Name = "Cine Grand"
                        },
                        new
                        {
                            Id = new Guid("c732801a-750e-4cf3-b1c3-a49aa055c214"),
                            Location = "Gabrovo",
                            Name = "Cine Grand"
                        },
                        new
                        {
                            Id = new Guid("f9ab2f51-2ecc-40cf-a229-37a76d8a42eb"),
                            Location = "Asenovgrad",
                            Name = "Cine Grand"
                        },
                        new
                        {
                            Id = new Guid("b9556a9b-b854-4b15-a7cb-5029d2f59ba8"),
                            Location = "Kazanlak",
                            Name = "Cine Grand"
                        });
                });

            modelBuilder.Entity("CinemaApp.Data.Models.CinemaMovie", b =>
                {
                    b.Property<Guid>("CinemaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CinemaId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("CinemasMovies");
                });

            modelBuilder.Entity("CinemaApp.Data.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8766ca7f-8ca1-494f-9a13-0abc29952e36"),
                            Description = "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
                            Director = "Lana Wachowski",
                            Duration = 136,
                            Genre = "Action",
                            ReleaseDate = new DateTime(1999, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = new Guid("1fc3fc65-612c-4cf4-bc4c-d0a90e92bc5c"),
                            Description = "Two imprisoned",
                            Director = "Frank Darabont",
                            Duration = 142,
                            Genre = "Drama",
                            ReleaseDate = new DateTime(1994, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = new Guid("97f5ea67-60b7-4324-9478-f038f8454276"),
                            Description = "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
                            Director = "Francis Ford Coppola",
                            Duration = 175,
                            Genre = "Crime",
                            ReleaseDate = new DateTime(1972, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Godfather"
                        });
                });

            modelBuilder.Entity("CinemaApp.Data.Models.CinemaMovie", b =>
                {
                    b.HasOne("CinemaApp.Data.Models.Cinema", "Cinema")
                        .WithMany("CinemaMovies")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CinemaApp.Data.Models.Movie", "Movie")
                        .WithMany("MovieCinemas")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaApp.Data.Models.Cinema", b =>
                {
                    b.Navigation("CinemaMovies");
                });

            modelBuilder.Entity("CinemaApp.Data.Models.Movie", b =>
                {
                    b.Navigation("MovieCinemas");
                });
#pragma warning restore 612, 618
        }
    }
}
